// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PriceTrackerCloud.Infrastructure.Data;

#nullable disable

namespace PriceTrackerCloud.Infrastructure.Data.Migrations
{
    [DbContext(typeof(PriceTrackerDbContext))]
    [Migration("20260614101347_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PriceTrackerCloud.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TargetPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("PriceTrackerCloud.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2b2b2b2-0000-0000-0000-000000000001"),
                            Category = "Videojuegos",
                            Description = "Consola Sony PS5 Standard Edition",
                            Name = "PlayStation 5"
                        },
                        new
                        {
                            Id = new Guid("b2b2b2b2-0000-0000-0000-000000000002"),
                            Category = "Smartphones",
                            Description = "Apple iPhone 15 Pro 256GB",
                            Name = "iPhone 15 Pro"
                        },
                        new
                        {
                            Id = new Guid("b2b2b2b2-0000-0000-0000-000000000003"),
                            Category = "Portátiles",
                            Description = "Apple MacBook Pro 14\" chip M3",
                            Name = "MacBook Pro 14 M3"
                        });
                });

            modelBuilder.Entity("PriceTrackerCloud.Domain.Entities.ProductPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCollected")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.HasIndex("ProductId", "StoreId", "DateCollected");

                    b.ToTable("ProductPrices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3c3c3c3-0000-0000-0000-000000000001"),
                            DateCollected = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 549.99m,
                            ProductId = new Guid("b2b2b2b2-0000-0000-0000-000000000001"),
                            StoreId = new Guid("a1a1a1a1-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-0000-0000-0000-000000000002"),
                            DateCollected = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 559.99m,
                            ProductId = new Guid("b2b2b2b2-0000-0000-0000-000000000001"),
                            StoreId = new Guid("a1a1a1a1-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-0000-0000-0000-000000000003"),
                            DateCollected = new DateTime(2026, 5, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 539.99m,
                            ProductId = new Guid("b2b2b2b2-0000-0000-0000-000000000001"),
                            StoreId = new Guid("a1a1a1a1-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-0000-0000-0000-000000000004"),
                            DateCollected = new DateTime(2026, 5, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 549.99m,
                            ProductId = new Guid("b2b2b2b2-0000-0000-0000-000000000001"),
                            StoreId = new Guid("a1a1a1a1-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-0000-0000-0000-000000000005"),
                            DateCollected = new DateTime(2026, 5, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 529.99m,
                            ProductId = new Guid("b2b2b2b2-0000-0000-0000-000000000001"),
                            StoreId = new Guid("a1a1a1a1-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-0000-0000-0000-000000000006"),
                            DateCollected = new DateTime(2026, 5, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 549.99m,
                            ProductId = new Guid("b2b2b2b2-0000-0000-0000-000000000001"),
                            StoreId = new Guid("a1a1a1a1-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-0000-0000-0000-000000000007"),
                            DateCollected = new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 519.99m,
                            ProductId = new Guid("b2b2b2b2-0000-0000-0000-000000000001"),
                            StoreId = new Guid("a1a1a1a1-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-0000-0000-0000-000000000008"),
                            DateCollected = new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 539.99m,
                            ProductId = new Guid("b2b2b2b2-0000-0000-0000-000000000001"),
                            StoreId = new Guid("a1a1a1a1-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-0000-0000-0000-000000000009"),
                            DateCollected = new DateTime(2026, 5, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 509.99m,
                            ProductId = new Guid("b2b2b2b2-0000-0000-0000-000000000001"),
                            StoreId = new Guid("a1a1a1a1-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-0000-0000-0000-000000000010"),
                            DateCollected = new DateTime(2026, 5, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 529.99m,
                            ProductId = new Guid("b2b2b2b2-0000-0000-0000-000000000001"),
                            StoreId = new Guid("a1a1a1a1-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-0000-0000-0000-000000000011"),
                            DateCollected = new DateTime(2026, 5, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 499.99m,
                            ProductId = new Guid("b2b2b2b2-0000-0000-0000-000000000001"),
                            StoreId = new Guid("a1a1a1a1-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-0000-0000-0000-000000000012"),
                            DateCollected = new DateTime(2026, 5, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 519.99m,
                            ProductId = new Guid("b2b2b2b2-0000-0000-0000-000000000001"),
                            StoreId = new Guid("a1a1a1a1-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-0000-0000-0000-000000000013"),
                            DateCollected = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 1229.00m,
                            ProductId = new Guid("b2b2b2b2-0000-0000-0000-000000000002"),
                            StoreId = new Guid("a1a1a1a1-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-0000-0000-0000-000000000014"),
                            DateCollected = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 1249.00m,
                            ProductId = new Guid("b2b2b2b2-0000-0000-0000-000000000002"),
                            StoreId = new Guid("a1a1a1a1-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-0000-0000-0000-000000000015"),
                            DateCollected = new DateTime(2026, 5, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 1219.00m,
                            ProductId = new Guid("b2b2b2b2-0000-0000-0000-000000000002"),
                            StoreId = new Guid("a1a1a1a1-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-0000-0000-0000-000000000016"),
                            DateCollected = new DateTime(2026, 5, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 1249.00m,
                            ProductId = new Guid("b2b2b2b2-0000-0000-0000-000000000002"),
                            StoreId = new Guid("a1a1a1a1-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-0000-0000-0000-000000000017"),
                            DateCollected = new DateTime(2026, 5, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 1199.00m,
                            ProductId = new Guid("b2b2b2b2-0000-0000-0000-000000000002"),
                            StoreId = new Guid("a1a1a1a1-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-0000-0000-0000-000000000018"),
                            DateCollected = new DateTime(2026, 5, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 1229.00m,
                            ProductId = new Guid("b2b2b2b2-0000-0000-0000-000000000002"),
                            StoreId = new Guid("a1a1a1a1-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-0000-0000-0000-000000000019"),
                            DateCollected = new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 1189.00m,
                            ProductId = new Guid("b2b2b2b2-0000-0000-0000-000000000002"),
                            StoreId = new Guid("a1a1a1a1-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-0000-0000-0000-000000000020"),
                            DateCollected = new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 1209.00m,
                            ProductId = new Guid("b2b2b2b2-0000-0000-0000-000000000002"),
                            StoreId = new Guid("a1a1a1a1-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-0000-0000-0000-000000000021"),
                            DateCollected = new DateTime(2026, 5, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 1179.00m,
                            ProductId = new Guid("b2b2b2b2-0000-0000-0000-000000000002"),
                            StoreId = new Guid("a1a1a1a1-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-0000-0000-0000-000000000022"),
                            DateCollected = new DateTime(2026, 5, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 1199.00m,
                            ProductId = new Guid("b2b2b2b2-0000-0000-0000-000000000002"),
                            StoreId = new Guid("a1a1a1a1-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-0000-0000-0000-000000000023"),
                            DateCollected = new DateTime(2026, 5, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 1169.00m,
                            ProductId = new Guid("b2b2b2b2-0000-0000-0000-000000000002"),
                            StoreId = new Guid("a1a1a1a1-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-0000-0000-0000-000000000024"),
                            DateCollected = new DateTime(2026, 5, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 1189.00m,
                            ProductId = new Guid("b2b2b2b2-0000-0000-0000-000000000002"),
                            StoreId = new Guid("a1a1a1a1-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-0000-0000-0000-000000000025"),
                            DateCollected = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 2199.00m,
                            ProductId = new Guid("b2b2b2b2-0000-0000-0000-000000000003"),
                            StoreId = new Guid("a1a1a1a1-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-0000-0000-0000-000000000026"),
                            DateCollected = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 2249.00m,
                            ProductId = new Guid("b2b2b2b2-0000-0000-0000-000000000003"),
                            StoreId = new Guid("a1a1a1a1-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-0000-0000-0000-000000000027"),
                            DateCollected = new DateTime(2026, 5, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 2149.00m,
                            ProductId = new Guid("b2b2b2b2-0000-0000-0000-000000000003"),
                            StoreId = new Guid("a1a1a1a1-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-0000-0000-0000-000000000028"),
                            DateCollected = new DateTime(2026, 5, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 2199.00m,
                            ProductId = new Guid("b2b2b2b2-0000-0000-0000-000000000003"),
                            StoreId = new Guid("a1a1a1a1-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-0000-0000-0000-000000000029"),
                            DateCollected = new DateTime(2026, 5, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 2099.00m,
                            ProductId = new Guid("b2b2b2b2-0000-0000-0000-000000000003"),
                            StoreId = new Guid("a1a1a1a1-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-0000-0000-0000-000000000030"),
                            DateCollected = new DateTime(2026, 5, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 2149.00m,
                            ProductId = new Guid("b2b2b2b2-0000-0000-0000-000000000003"),
                            StoreId = new Guid("a1a1a1a1-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-0000-0000-0000-000000000031"),
                            DateCollected = new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 2049.00m,
                            ProductId = new Guid("b2b2b2b2-0000-0000-0000-000000000003"),
                            StoreId = new Guid("a1a1a1a1-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-0000-0000-0000-000000000032"),
                            DateCollected = new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 2099.00m,
                            ProductId = new Guid("b2b2b2b2-0000-0000-0000-000000000003"),
                            StoreId = new Guid("a1a1a1a1-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-0000-0000-0000-000000000033"),
                            DateCollected = new DateTime(2026, 5, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 1999.00m,
                            ProductId = new Guid("b2b2b2b2-0000-0000-0000-000000000003"),
                            StoreId = new Guid("a1a1a1a1-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-0000-0000-0000-000000000034"),
                            DateCollected = new DateTime(2026, 5, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 2049.00m,
                            ProductId = new Guid("b2b2b2b2-0000-0000-0000-000000000003"),
                            StoreId = new Guid("a1a1a1a1-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-0000-0000-0000-000000000035"),
                            DateCollected = new DateTime(2026, 5, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 1979.00m,
                            ProductId = new Guid("b2b2b2b2-0000-0000-0000-000000000003"),
                            StoreId = new Guid("a1a1a1a1-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-0000-0000-0000-000000000036"),
                            DateCollected = new DateTime(2026, 5, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 1999.00m,
                            ProductId = new Guid("b2b2b2b2-0000-0000-0000-000000000003"),
                            StoreId = new Guid("a1a1a1a1-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("PriceTrackerCloud.Domain.Entities.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1a1a1a1-0000-0000-0000-000000000001"),
                            Name = "Amazon",
                            Website = "https://www.amazon.es"
                        },
                        new
                        {
                            Id = new Guid("a1a1a1a1-0000-0000-0000-000000000002"),
                            Name = "PcComponentes",
                            Website = "https://www.pccomponentes.com"
                        },
                        new
                        {
                            Id = new Guid("a1a1a1a1-0000-0000-0000-000000000003"),
                            Name = "MediaMarkt",
                            Website = "https://www.mediamarkt.es"
                        },
                        new
                        {
                            Id = new Guid("a1a1a1a1-0000-0000-0000-000000000004"),
                            Name = "El Corte Inglés",
                            Website = "https://www.elcorteingles.es"
                        });
                });

            modelBuilder.Entity("PriceTrackerCloud.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PriceTrackerCloud.Domain.Entities.Alert", b =>
                {
                    b.HasOne("PriceTrackerCloud.Domain.Entities.Product", "Product")
                        .WithMany("Alerts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PriceTrackerCloud.Domain.Entities.User", "User")
                        .WithMany("Alerts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PriceTrackerCloud.Domain.Entities.ProductPrice", b =>
                {
                    b.HasOne("PriceTrackerCloud.Domain.Entities.Product", "Product")
                        .WithMany("Prices")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PriceTrackerCloud.Domain.Entities.Store", "Store")
                        .WithMany("Prices")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("PriceTrackerCloud.Domain.Entities.Product", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Prices");
                });

            modelBuilder.Entity("PriceTrackerCloud.Domain.Entities.Store", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("PriceTrackerCloud.Domain.Entities.User", b =>
                {
                    b.Navigation("Alerts");
                });
#pragma warning restore 612, 618
        }
    }
}
